#!/usr/bin/env bash
# This script displays "FizzBuzz" when the number is a multiple of 3 and 5
#+ displays Fizz when the number is multiple of 3
#+ displays Buzz when the number is a multiple of 5
for ((i=1; i<=100; i++))
do
	((modfive = i % 5))
	((modthree = i % 3))
	if [ $modfive -eq 0 ] && [ $modthree -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $modthree -eq 0 ]
	then
		echo "Fizz"
	elif [ $modfive -eq 0 ]
	then
		echo "Buzz"
	else
		echo $i
	fi
done
